 const str  = `getUniqueId: import("./internal/privateTypes").Getter<Promise<string>>, getUniqueIdSync: import("./internal/privateTypes").Getter<string>;
 syncUniqueId(): Promise<string>;
 getInstanceId: import("./internal/privateTypes").Getter<Promise<string>>, getInstanceIdSync: import("./internal/privateTypes").Getter<string>;
 getSerialNumber: import("./internal/privateTypes").Getter<Promise<string>>, getSerialNumberSync: import("./internal/privateTypes").Getter<string>;
 getAndroidId: import("./internal/privateTypes").Getter<Promise<string>>, getAndroidIdSync: import("./internal/privateTypes").Getter<string>;
 getIpAddress: import("./internal/privateTypes").Getter<Promise<string>>, getIpAddressSync: import("./internal/privateTypes").Getter<string>;
 isCameraPresent: import("./internal/privateTypes").Getter<Promise<boolean>>, isCameraPresentSync: import("./internal/privateTypes").Getter<boolean>;
 getMacAddress(): Promise<string>;
 getMacAddressSync(): string;
 getDeviceId: () => string;
 getManufacturer: import("./internal/privateTypes").Getter<Promise<string>>, getManufacturerSync: import("./internal/privateTypes").Getter<string>;
 getModel: () => string;
 getBrand: () => string;
 getSystemName: () => string;
 getSystemVersion: () => string;
 getBuildId: import("./internal/privateTypes").Getter<Promise<string>>, getBuildIdSync: import("./internal/privateTypes").Getter<string>;
 getApiLevel: import("./internal/privateTypes").Getter<Promise<number>>, getApiLevelSync: import("./internal/privateTypes").Getter<number>;
 getBundleId: () => string;
 getInstallerPackageName: import("./internal/privateTypes").Getter<Promise<string>>, getInstallerPackageNameSync: import("./internal/privateTypes").Getter<string>;
 getApplicationName: () => string;
 getBuildNumber: () => string;
 getVersion: () => string;
 getReadableVersion(): string;
 getDeviceName: import("./internal/privateTypes").Getter<Promise<string>>, getDeviceNameSync: import("./internal/privateTypes").Getter<string>;
 getUsedMemory: import("./internal/privateTypes").Getter<Promise<number>>, getUsedMemorySync: import("./internal/privateTypes").Getter<number>;
 getUserAgent: () => Promise<string>;
 getUserAgentSync: () => string;
 getFontScale: import("./internal/privateTypes").Getter<Promise<number>>, getFontScaleSync: import("./internal/privateTypes").Getter<number>;
 getBootloader: import("./internal/privateTypes").Getter<Promise<string>>, getBootloaderSync: import("./internal/privateTypes").Getter<string>;
 getDevice: import("./internal/privateTypes").Getter<Promise<string>>, getDeviceSync: import("./internal/privateTypes").Getter<string>;
 getDisplay: import("./internal/privateTypes").Getter<Promise<string>>, getDisplaySync: import("./internal/privateTypes").Getter<string>;
 getFingerprint: import("./internal/privateTypes").Getter<Promise<string>>, getFingerprintSync: import("./internal/privateTypes").Getter<string>;
 getHardware: import("./internal/privateTypes").Getter<Promise<string>>, getHardwareSync: import("./internal/privateTypes").Getter<string>;
 getHost: import("./internal/privateTypes").Getter<Promise<string>>, getHostSync: import("./internal/privateTypes").Getter<string>;
 getHostNames: import("./internal/privateTypes").Getter<Promise<string[]>>, getHostNamesSync: import("./internal/privateTypes").Getter<string[]>;
 getProduct: import("./internal/privateTypes").Getter<Promise<string>>, getProductSync: import("./internal/privateTypes").Getter<string>;
 getTags: import("./internal/privateTypes").Getter<Promise<string>>, getTagsSync: import("./internal/privateTypes").Getter<string>;
 getType: import("./internal/privateTypes").Getter<Promise<string>>, getTypeSync: import("./internal/privateTypes").Getter<string>;
 getBaseOs: import("./internal/privateTypes").Getter<Promise<string>>, getBaseOsSync: import("./internal/privateTypes").Getter<string>;
 getPreviewSdkInt: import("./internal/privateTypes").Getter<Promise<number>>, getPreviewSdkIntSync: import("./internal/privateTypes").Getter<number>;
 getSecurityPatch: import("./internal/privateTypes").Getter<Promise<string>>, getSecurityPatchSync: import("./internal/privateTypes").Getter<string>;
 getCodename: import("./internal/privateTypes").Getter<Promise<string>>, getCodenameSync: import("./internal/privateTypes").Getter<string>;
 getIncremental: import("./internal/privateTypes").Getter<Promise<string>>, getIncrementalSync: import("./internal/privateTypes").Getter<string>;
 isEmulator: import("./internal/privateTypes").Getter<Promise<boolean>>, isEmulatorSync: import("./internal/privateTypes").Getter<boolean>;
 isTablet: () => boolean;
 isLowRamDevice: () => boolean;
 isDisplayZoomed: () => boolean;
 isPinOrFingerprintSet: import("./internal/privateTypes").Getter<Promise<boolean>>, isPinOrFingerprintSetSync: import("./internal/privateTypes").Getter<boolean>;
 hasNotch(): boolean;
 hasDynamicIsland(): boolean;
 hasGms: import("./internal/privateTypes").Getter<Promise<boolean>>, hasGmsSync: import("./internal/privateTypes").Getter<boolean>;
 hasHms: import("./internal/privateTypes").Getter<Promise<boolean>>, hasHmsSync: import("./internal/privateTypes").Getter<boolean>;
 getFirstInstallTime: import("./internal/privateTypes").Getter<Promise<number>>, getFirstInstallTimeSync: import("./internal/privateTypes").Getter<number>;
 getInstallReferrer: import("./internal/privateTypes").Getter<Promise<string>>, getInstallReferrerSync: import("./internal/privateTypes").Getter<string>;
 getLastUpdateTime: import("./internal/privateTypes").Getter<Promise<number>>, getLastUpdateTimeSync: import("./internal/privateTypes").Getter<number>;
 getStartupTime: import("./internal/privateTypes").Getter<Promise<number>>, getStartupTimeSync: import("./internal/privateTypes").Getter<number>;
 getCarrier: import("./internal/privateTypes").Getter<Promise<string>>, getCarrierSync: import("./internal/privateTypes").Getter<string>;
 getTotalMemory: import("./internal/privateTypes").Getter<Promise<number>>, getTotalMemorySync: import("./internal/privateTypes").Getter<number>;
 getMaxMemory: import("./internal/privateTypes").Getter<Promise<number>>, getMaxMemorySync: import("./internal/privateTypes").Getter<number>;
 getTotalDiskCapacity: import("./internal/privateTypes").Getter<Promise<number>>, getTotalDiskCapacitySync: import("./internal/privateTypes").Getter<number>;
 getTotalDiskCapacityOld(): Promise<number>;
 getTotalDiskCapacityOldSync(): number;
 getFreeDiskStorage: import("./internal/privateTypes").Getter<Promise<number>>, getFreeDiskStorageSync: import("./internal/privateTypes").Getter<number>;
 getFreeDiskStorageOld(): Promise<number>;
 getFreeDiskStorageOldSync(): number;
 getBatteryLevel: import("./internal/privateTypes").Getter<Promise<number>>, getBatteryLevelSync: import("./internal/privateTypes").Getter<number>;
 getPowerState: import("./internal/privateTypes").Getter<Promise<Partial<PowerState>>>, getPowerStateSync: import("./internal/privateTypes").Getter<Partial<PowerState>>;
 isBatteryCharging: import("./internal/privateTypes").Getter<Promise<boolean>>, isBatteryChargingSync: import("./internal/privateTypes").Getter<boolean>;
 isLandscape(): Promise<boolean>;
 isLandscapeSync(): boolean;
 isAirplaneMode: import("./internal/privateTypes").Getter<Promise<boolean>>, isAirplaneModeSync: import("./internal/privateTypes").Getter<boolean>;
 getDeviceType: () => string;
 getDeviceTypeSync: () => string;
 supportedAbis: import("./internal/privateTypes").Getter<Promise<string[]>>, supportedAbisSync: import("./internal/privateTypes").Getter<string[]>;
 supported32BitAbis: import("./internal/privateTypes").Getter<Promise<string[]>>, supported32BitAbisSync: import("./internal/privateTypes").Getter<string[]>;
 supported64BitAbis: import("./internal/privateTypes").Getter<Promise<string[]>>, supported64BitAbisSync: import("./internal/privateTypes").Getter<string[]>;
 hasSystemFeature(feature: string): Promise<boolean>;
 hasSystemFeatureSync(feature: string): boolean;
 isLowBatteryLevel(level: number): boolean;
 getSystemAvailableFeatures: import("./internal/privateTypes").Getter<Promise<string[]>>, getSystemAvailableFeaturesSync: import("./internal/privateTypes").Getter<string[]>;
 isLocationEnabled: import("./internal/privateTypes").Getter<Promise<boolean>>, isLocationEnabledSync: import("./internal/privateTypes").Getter<boolean>;
 isHeadphonesConnected: import("./internal/privateTypes").Getter<Promise<boolean>>, isHeadphonesConnectedSync: import("./internal/privateTypes").Getter<boolean>;
 isWiredHeadphonesConnected: import("./internal/privateTypes").Getter<Promise<boolean>>, isWiredHeadphonesConnectedSync: import("./internal/privateTypes").Getter<boolean>;
 isBluetoothHeadphonesConnected: import("./internal/privateTypes").Getter<Promise<boolean>>, isBluetoothHeadphonesConnectedSync: import("./internal/privateTypes").Getter<boolean>;
 isMouseConnected: import("./internal/privateTypes").Getter<Promise<boolean>>, isMouseConnectedSync: import("./internal/privateTypes").Getter<boolean>;
 isKeyboardConnected: import("./internal/privateTypes").Getter<Promise<boolean>>, isKeyboardConnectedSync: import("./internal/privateTypes").Getter<boolean>;
 getSupportedMediaTypeList: import("./internal/privateTypes").Getter<Promise<string[]>>, getSupportedMediaTypeListSync: import("./internal/privateTypes").Getter<string[]>;
 isTabletMode: () => Promise<boolean>;
 getAvailableLocationProviders: import("./internal/privateTypes").Getter<Promise<LocationProviderInfo>>, getAvailableLocationProvidersSync: import("./internal/privateTypes").Getter<LocationProviderInfo>;
 getBrightness: import("./internal/privateTypes").Getter<Promise<number>>, getBrightnessSync: import("./internal/privateTypes").Getter<number>`;

str.split(":").forEach(i=>i.split(";").forEach(name=>{
  
}));